name: Release

on:
  push:
    tags:
      - 'v*.*.*'

env:
  CARGO_TERM_COLOR: always

jobs:
  build-release:
    name: Build Release
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            artifact_name: exceldiff
            asset_name: exceldiff-linux-x86_64
# Temporarily disabled as the aarch64 build is failing
#          - os: ubuntu-latest
#            target: aarch64-unknown-linux-gnu
#            artifact_name: exceldiff
#            asset_name: exceldiff-linux-aarch64
          - os: macos-latest
            target: aarch64-apple-darwin
            artifact_name: exceldiff
            asset_name: exceldiff-macos-arm64
          - os: macos-latest
            target: x86_64-apple-darwin
            artifact_name: exceldiff
            asset_name: exceldiff-macos-x86_64

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get version from tag
        id: get_version
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Version: $VERSION"

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Install cross-compilation tools (Linux ARM64)
        if: matrix.target == 'aarch64-unknown-linux-gnu'
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-aarch64-linux-gnu

      - name: Build
        env:
          VERSION: ${{ steps.get_version.outputs.version }}
        run: |
          cargo build --release --target ${{ matrix.target }}

      - name: Strip binary (Linux)
        if: startsWith(matrix.os, 'ubuntu')
        run: |
          if [ "${{ matrix.target }}" = "aarch64-unknown-linux-gnu" ]; then
            aarch64-linux-gnu-strip target/${{ matrix.target }}/release/${{ matrix.artifact_name }}
          else
            strip target/${{ matrix.target }}/release/${{ matrix.artifact_name }}
          fi

      - name: Strip binary (macOS)
        if: startsWith(matrix.os, 'macos')
        run: strip target/${{ matrix.target }}/release/${{ matrix.artifact_name }}

      - name: Rename binary
        run: |
          cp target/${{ matrix.target }}/release/${{ matrix.artifact_name }} ${{ matrix.asset_name }}

      - name: Generate SHA256 checksum
        run: |
          shasum -a 256 ${{ matrix.asset_name }} > ${{ matrix.asset_name }}.sha256

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.asset_name }}
          path: |
            ${{ matrix.asset_name }}
            ${{ matrix.asset_name }}.sha256
          if-no-files-found: error

  create-release:
    name: Create Release
    # Only run if ALL platform builds succeed
    needs: build-release
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get version from tag
        id: get_version
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Version: $VERSION"

      - name: Extract changelog for version
        id: changelog
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          awk "/## \[$VERSION\]/,/## \[/" CHANGELOG.md | sed '1d;$d' > release_notes.md
          if [ ! -s release_notes.md ]; then
            echo "Release version $VERSION" > release_notes.md
          fi
          cat release_notes.md

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
          merge-multiple: true

      - name: List artifacts
        run: ls -la artifacts/

      - name: Verify all expected artifacts are present
        # Add aarch64-unknown-linux-gnu to the assets once the build is fixed
        run: |
          echo "Verifying all 4 platform binaries and checksums are present..."
          for asset in exceldiff-linux-x86_64 exceldiff-macos-arm64 exceldiff-macos-x86_64; do
            if [ ! -f "artifacts/$asset" ]; then
              echo "ERROR: Missing binary: $asset"
              exit 1
            fi
            if [ ! -f "artifacts/$asset.sha256" ]; then
              echo "ERROR: Missing checksum: $asset.sha256"
              exit 1
            fi
            echo "✓ Found: $asset and $asset.sha256"
          done
          echo "All artifacts verified successfully!"

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          name: Release ${{ steps.get_version.outputs.version }}
          body_path: release_notes.md
          draft: false
          prerelease: false
          files: |
            artifacts/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
